version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            bundle install
      - run:
          name: Build project
          command: bundle exec jekyll build
  deploy-to-ghpages:
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            bundle install
      - run:
          name: Git user config
          command: git config --global user.name "BB pipeline" && git config --global user.email "pipeline@reyesoft.com"
      - run:
          name: Publish to Github Pages
          command: |
            git checkout -b temp-deploy-branch
            rm .gitignore
            git add .
            git commit -m "Deploying..."
            git push --set-upstream origin temp-deploy-branch
            bundle exec jgd -r temp-deploy-branch
            git checkout master
            git push origin --delete temp-deploy-branch

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  deploy:
    jobs:
      - deploy-to-ghpages:
          filters:
            branches:
              only: master
