version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            bundle install
      - run:
          name: Build project
          command: bundle exec jekyll build
  deploy-to-ghpages:
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            bundle install
      - run:
          name: Git user config
          command: git config --global user.name "BB pipeline" && git config --global user.email "pipeline@reyesoft.com"
      - run:
          name: Publish to Github Pages
          command: |
            rm .gitignore
            bundle exec jgd
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  deploy:
    jobs:
      - deploy-to-ghpages:
          filters:
            branches:
              only: master
